-- Seed AI Models
-- This migration populates the ai_models table with current model data

INSERT INTO ai_models (id, model_id, provider, display_name, family, version, tier, context_window, max_output_tokens, input_cost_per_1m_tokens, output_cost_per_1m_tokens, capabilities, sdk_supported, is_latest, is_default, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'claude-opus-4-20250514', 'anthropic', 'Opus', 'opus', '4', 'ultra', 200000, 32000, '15.00', '75.00', '{"reasoning": true, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "excellent", "creativeWriting": "excellent", "analysis": "excellent"}', true, true, true, NOW(), NOW()),
  (gen_random_uuid(), 'claude-sonnet-4-20250514', 'anthropic', 'Sonnet', 'sonnet', '4', 'powerful', 200000, 16000, '3.00', '15.00', '{"reasoning": true, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "excellent", "creativeWriting": "good", "analysis": "excellent"}', true, true, true, NOW(), NOW()),
  (gen_random_uuid(), 'claude-haiku-4-5-20251001', 'anthropic', 'Haiku', 'haiku', '4.5', 'fast', 200000, 8192, '0.80', '4.00', '{"reasoning": false, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "good", "creativeWriting": "basic", "analysis": "good"}', true, true, true, NOW(), NOW()),
  (gen_random_uuid(), 'gpt-5', 'openai', 'GPT', 'gpt', '5', 'powerful', 128000, 16384, '2.00', '8.00', '{"reasoning": true, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "excellent", "creativeWriting": "good", "analysis": "excellent"}', true, true, true, NOW(), NOW()),
  (gen_random_uuid(), 'gpt-5-mini', 'openai', 'GPT Mini', 'gpt-mini', '5', 'fast', 128000, 16384, '0.30', '1.25', '{"reasoning": false, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "good", "creativeWriting": "basic", "analysis": "good"}', true, true, true, NOW(), NOW()),
  (gen_random_uuid(), 'gpt-4.1', 'openai', 'GPT 4.1', 'gpt-4.1', '4.1', 'balanced', 1047576, 32768, '2.00', '8.00', '{"reasoning": true, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "excellent", "creativeWriting": "good", "analysis": "excellent"}', true, true, false, NOW(), NOW()),
  (gen_random_uuid(), 'gpt-4.1-mini', 'openai', 'GPT 4.1 Mini', 'gpt-4.1-mini', '4.1', 'fast', 1047576, 32768, '0.40', '1.60', '{"reasoning": false, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "good", "creativeWriting": "basic", "analysis": "good"}', true, true, false, NOW(), NOW()),
  (gen_random_uuid(), 'o3', 'openai', 'o3', 'o-series', '3', 'ultra', 200000, 100000, '2.00', '8.00', '{"reasoning": true, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "excellent", "creativeWriting": "good", "analysis": "excellent"}', true, true, true, NOW(), NOW()),
  (gen_random_uuid(), 'o4-mini', 'openai', 'o4 Mini', 'o-series-mini', '4', 'balanced', 200000, 100000, '1.10', '4.40', '{"reasoning": true, "vision": true, "toolUse": true, "streaming": true, "structuredOutput": true, "codeGeneration": "good", "creativeWriting": "basic", "analysis": "good"}', true, true, true, NOW(), NOW()),
  (gen_random_uuid(), 'llama3.2', 'ollama', 'Llama 3.2', 'llama', '3.2', 'balanced', 128000, NULL, '0', '0', '{"reasoning": false, "vision": false, "toolUse": false, "streaming": true, "structuredOutput": false, "codeGeneration": "basic", "creativeWriting": "basic", "analysis": "basic"}', true, true, true, NOW(), NOW())
ON CONFLICT (model_id) DO NOTHING;
